[autostart]
exec = [
	"xsetroot -cursor_name left_ptr"
]

[settings]
	# Window settings
	gapSize = 7
	borderWidth = 2
	borderColorUnfocused = "#7197E7"
	borderColorFocused = "#A77AC4"
	borderColorUrgent = "#E06C75"
	# Bar settings
	barHeight = 19
	windowTitlePosition = "left"
	barBackgroundColor = "#282C34"
	barForegroundColor = "#F8F8F2"
	barSelectionColor = "#A77AC4"
	barUrgentColor = "#E06C75"
	barFonts = [
		"JetBrains Mono:size=8:antialias=true",
		"Font Awesome 5 Free Solid:size=9:antialias=true",
		"DejaVu Serif:size=8:antialias=true",
	]
	# General settings
	loggingEnabled = false

[[appRule]]
class = "discord"
monitor = 2
tags = [ 1 ]

[[appRule]]
class = "Slack"
monitor = 2
tags = [ 2 ]

[[appRule]]
class = "TelegramDesktop"
monitor = 2
tags = [ 3 ]

[[appRule]]
class = "Spotify"
monitor = 2
tags = [ 4 ]
